version: '3.7'
services:
  database:
    image: postgres:12.2-alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - PG_DATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=application
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=P@ssw0rd

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
    - ./:/app
    environment:
      - DB_HOST=database
      - DB_NAME=application
      - DB_USER=application
      - DB_PASSWORD=P@ssw0rd
      - DB_ADAPTER=postgresql
      - RAILS_ENV=development
    depends_on:
      - database
