version: '3.7'
services:
  database:
    image: postgres:12.2-alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
    - ./:/app
    env_file:
      - .env
    depends_on:
      - database
